openapi: 3.0.3
info:
  title: inventory
  description: Manages inventory caps
  version: 1.3.0
  contact:
    name: Finance Chapter
    url: >-
      https://evenfinancial.atlassian.net/wiki/spaces/ENG/pages/363167994/Finance+Chapter
servers:
  - url: 'https://api.evenfinancial.com/inventory'
    description: Prod
  - url: 'https://dev-api.evenfinancial.com/inventory'
    description: Dev
components:
  x-lint-skip:
    - inline-schema-is-scalar
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /auth/accessTokens
          scopes:
            'inventory:read': Allows read access to inventory endpoints
            'inventory:write': Allows write access to inventory endpoints
tags:
  - name: Demand Sub-Account Inventory Cap
    description: >-
      Inventory caps set against demand sub-accounts. A means to control the
      amount of traffic going towards a specific demand sub-account
  - name: Static Offer Inventory Cap
    description: >-
      Inventory caps set against static offers. Represents a static offer that
      Partner Solutions does not want to have too high of an attributed revenue
      or attributed clicks
paths:
  /staticOfferInventoryCaps:
    get:
      x-lint-skip:
        - index-endpoint-has-limit
      summary: Get static offer inventory caps
      description: >-
        Return a list of StaticOfferInventoryCaps, filtered by search criteria
        provided in the URL
      operationId: getStaticOfferInventoryCaps
      tags:
        - Static Offer Inventory Cap
      security:
        - oauth:
            - 'inventory:read'
    post:
      summary: Create a static offer inventory cap
      description: create a static offer inventory cap
      operationId: createStaticOfferInventoryCap
      security:
        - oauth:
            - 'inventory:write'
      tags:
        - Static Offer Inventory Cap
  '/staticOfferInventoryCaps/{id}':
    delete:
      summary: Delete a static offer inventory cap
      description: Delete a static offer inventory cap
      operationId: deleteStaticOfferInventoryCap
      security:
        - oauth:
            - 'inventory:write'
      tags:
        - Static Offer Inventory Cap
    put:
      summary: Update a static offer inventory cap
      description: Update a static offer inventory cap
      operationId: updateStaticOfferInventoryCap
      security:
        - oauth:
            - 'inventory:write'
      tags:
        - Static Offer Inventory Cap
    get:
      summary: Get a static offer inventory cap
      description: Get a static offer inventory cap
      operationId: getStaticOfferInventoryCap
      security:
        - oauth:
            - 'inventory:read'
      tags:
        - Static Offer Inventory Cap
  '/staticOfferInventoryCaps/{id}/versionDiff':
    x-lint-skip:
      - path-resource-is-plural
    get:
      summary: Get a version diff of a static offer inventory cap
      description: Get a version diff of a static offer inventory cap
      operationId: getStaticOfferInventoryCapVersionDiff
      security:
        - oauth:
            - 'inventory:read'
      tags:
        - Static Offer Inventory Cap
  /filterDemandSubAccounts:
    get:
      summary: Filter capped sub-account IDs
      description: >
        Return a filtered list of sub-account IDs that have not reached cap
        limit,

        given a list of sub-account IDs
      operationId: filterCappedSubAccountIds
      tags:
        - Demand Sub-Account Inventory Cap
  /calculateDemandSubAccountCaps:
    post:
      summary: Refresh demand sub-account inventory cache
      description: |
        Refresh `DemandSubAccountInventoryCaps` cache manually
      operationId: refreshDemandSubAccountInventoryCache
      tags:
        - Demand Sub-Account Inventory Cap
  /demandSubAccountInventoryCaps:
    get:
      x-lint-skip:
        - index-endpoint-has-limit
      summary: Get demand sub-account inventory caps
      description: Return demand sub account inventory caps based upon request parameters
      operationId: getDemandSubAccountInventoryCaps
      security:
        - oauth:
            - 'inventory:read'
      tags:
        - Demand Sub-Account Inventory Cap
    post:
      summary: Create a demand sub-account inventory cap
      description: Create a demand-sub account inventory cap
      operationId: createDemandSubAccountInventoryCap
      security:
        - oauth:
            - 'inventory:write'
      tags:
        - Demand Sub-Account Inventory Cap
  '/demandSubAccountInventoryCaps/{id}':
    delete:
      summary: Delete a demand sub-account inventory cap
      description: Delete a demand sub-account inventory cap
      operationId: deleteDemandSubAccountInventoryCap
      security:
        - oauth:
            - 'inventory:write'
      tags:
        - Demand Sub-Account Inventory Cap
    put:
      summary: Update a demand sub-account inventory cap
      description: Update a demand sub0-account inventory cap
      operationId: updateDemandSubAccountInventoryCap
      security:
        - oauth:
            - 'inventory:write'
      tags:
        - Demand Sub-Account Inventory Cap
    get:
      summary: Get a demand sub-account inventory cap
      description: Get a demand sub-account inventory cap
      operationId: getDemandSubAccountInventoryCap
      security:
        - oauth:
            - 'inventory:read'
      tags:
        - Demand Sub-Account Inventory Cap
  /staticOfferInvetoryCapsStatuses:
    get:
      summary: Get static offer inventory cap statuses
      description: Get static offer inventory cap statuses
      operationId: getStaticOfferInventoryCapStatuses
      security:
        - oauth:
            - 'inventory:read'
      tags:
        - Static Offer Inventory Cap
  '/staticOfferInventoryCapsStatus/{id}':
    x-lint-skip:
      - path-resource-is-plural
    get:
      summary: Get the status of a static offer invetory cap
      description: Get the status of a static offer invetory cap
      operationId: getStaticOfferInventoryCapStatus
      security:
        - oauth:
            - 'inventory:read'
      tags:
        - Static Offer Inventory Cap